# Generated by Django 4.2.7 on 2023-12-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_persona_unique_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=400)),
            ],
        ),
    ]
