# Generated by Django 4.2.7 on 2023-12-01 12:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="unique_hash",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
