# Generated by Django 4.2.7 on 2023-12-01 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0010_project_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeanUXCanvas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_hash",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("business_problem", models.CharField(max_length=500)),
                ("primary_outcome", models.CharField(max_length=255)),
                ("secondary_outcomes", models.TextField()),
                ("primary_users", models.TextField()),
                ("secondary_users", models.TextField()),
                ("outcomes", models.TextField()),
                ("problems", models.TextField()),
                ("solution_ideas", models.TextField()),
                ("hypotheses", models.TextField()),
                ("assumptions", models.TextField()),
                ("experiment_what_to_test", models.TextField()),
                ("experiment_method", models.TextField()),
                ("experiment_success_metrics", models.TextField()),
                ("mvp_actions", models.TextField()),
                ("learning_metrics_tracking", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.project"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
