# Generated by Django 4.2.7 on 2023-12-01 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_leanuxcanvas"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leanuxcanvas",
            old_name="business_problem",
            new_name="problem",
        ),
    ]
