# Generated by Django 4.2.7 on 2023-12-01 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_rename_business_problem_leanuxcanvas_problem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leanuxcanvas",
            old_name="outcomes",
            new_name="user_outcomes",
        ),
        migrations.RenameField(
            model_name="leanuxcanvas",
            old_name="problems",
            new_name="user_problems",
        ),
    ]
